blocitoff/config/routes.rb
Rails.application.routes.draw do

  get '/', to: 'welcome#index'
  devise_for :users
  authenticate :user do
    root 'dashboard#index'
    resources :dashboard, only: [:index]
    resources :items do
      put :toggle
    end
    get 'input_task' => 'dashboard#new'
    
  end

end

blocitoff/app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  
end

blocitoff/app/models/user.rb
class User < ActiveRecord::Base
  has_many :items
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

blocitoff/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  # layout :layout
  
  # def layout
		# 	if !user_signed_in?
		# 		#return "devise_layout"

		# 		    return "../welcome/index"
		# 	else
		# 		return "../dashboard/index"
		# 	end
  # end
  
  def after_sign_in_path_for(resource)
  dashboard_index_path #or whatever path helper you need
  end
end

blocitoff/app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @items = Item.where(completed: false)
  end
  
  def new
    puts params
    user = current_user
    year = params[:date][:year]
    month = params[:date][:month]
    day = params[:date][:day]
    date = year.to_s+"/"+month.to_s+"/"+day.to_s
    realdate = DateTime.strptime(date,'%Y/%m/%d')
    description = params[:q]
    
    #insert task into database
    user.items.create(:description => description, :completion_date => realdate )
    
    
    render 'dashboard/index'
  end
  
  def destroy
    puts params
    render 'dashboard/index'
  end
end

blocitoff/app/controllers/items_controller.rb
class ItemsController < ApplicationController
#   layout false
  def toggle
   item = Item.find(params[:item_id])
   item.update_attributes(completed: !item.completed)
   redirect_to dashboard_index_path
  end
end

blocitoff/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!
  def index
  end
end

blocitoff/app/helpers/application_helper.rb
module ApplicationHelper
end

blocitoff/app/helpers/dashboard_helper.rb
module DashboardHelper
end

blocitoff/app/helpers/items_helper.rb
module ItemsHelper
end

blocitoff/app/helpers/welcome_helper.rb
module WelcomeHelper
end

blocitoff/app/views/dashboard/_new.html.erb
<br>
<br>
<br>
<div class="login-box" style="max-width: 500px;" id="login-box">
    <div class="login-logo">
      <a href="#"><b>B</b>loc<b>I</b>t<b>O</b>ff Task Creator</a>
    </div>
    <br>
    <div class="login-box-body">
        <%= form_tag("/input_task", method: "get") do %>
          <%= label_tag(:q, "Completion Date:") %>
          <%= select_year(Time.now) %>
          <%= select_month(Time.now) %>
          <%= select_day(Time.now) %>
          <br>
          <br>
          <%= label_tag(:q, "Description:") %>
          <%= text_area_tag(:q) %>
          <br>
          <br>
          <%= submit_tag("Create") %>
        <% end %>
    </div>
</div>

blocitoff/app/views/dashboard/index.html.erb
<div class="container">
  <div class="row" id="heading" >
        <h1 style="font-family: ""Comic Sans MS"", cursive, sans-serif;" >Your To Do List</h1>
        <div class="row" id=input>
            <%=render(:partial => 'dashboard/new') %>
            <br>
            <br>
        </div>
    </div>
        <div class="row" id="table_div" >
            <table id="to_do_list">
                <thead>
                  <tr>
                    <th>Description</th>
                    <th>Days to Completion</th>
                    <th>Mark as Complete</th>
                  </tr>
                </thead>
                <tbody>
                  <% @items.each do |item| %>
                    <tr>
                      <td><%= item.description %></td>
                      <% @days_left = distance_of_time_in_words_to_now(item.completion_date) %>
                      <td><%= @days_left %></td>
                      <td><%= link_to "", item_toggle_path(item), method: :put, class: 'glyphicon glyphicon-ok' %></td>
                    </tr>
                  <% end %>
                </tbody>
            </table>
        </div>
        
</div>

blocitoff/app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

blocitoff/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse">
    <div class="navbar-header">
        <a href='#' class="navbar-brand">BlocItOff</a>
    </div>
    <div>
        <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
            <li></li>
        </ul>
        
        <form class="navbar-form navbar-right">
            <input type="text" class="form-control" placeholder="search...">
        </form>
        
        <ul class="nav navbar-nav navbar-right">
            <li style="color:white" id="username">
                Welcome, <strong><%=current_user.email  %></strong>
            </li>
        </ul>
    </div>
</nav>

blocitoff/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocitoff</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <%= render(:partial => 'layouts/navbar') if current_user%>
        </div>

        <%= yield %>
        
    </div>
  
  

</body>
</html>

blocitoff/app/views/welcome/index.html.erb
 <br>
 <div class="container" ></div>
   <div class="jumbotron" id="jumbo" >
     <h1 style="color: darkcyan;"><b>B</b>loc<b>I</b>t<b>O</b>ff</h1>
     <p><b>B</b>loc<b>I</b>t<b>O</b>ff your one-stop-shop checklist</p>
     <p>
       <%= link_to "Sign In", new_user_session_path %> or
       <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %> today!
     </p>
     <br>
     <img alt="The Ultimate To Do List" src="/assets/to-do-list.png" class="pull-right" id="picture" />
   </div>
   
   <div id="firststatement" >
     <div class="col-md-8" >
       <h2>Keep track of that busy life</h2>
       <p><b>B</b>loc<b>I</b>t<b>O</b>ff will track your critical taks, from anywhere in the world.</p>
     </div>
     <br>
     <div class="col-md-8">
       <h2>Check items off when they are complete</h2>
       <p><b>B</b>loc<b>I</b>t<b>O</b>ff enables you to check off your tasks once they are complete.</p>
     </div>
   </div>
 </div>